---
api:
    host: ""
    port: 8010
    staticPath: ./static

db:
    host: postgres
    port: 6634
    username: anwil
    databaseName: postgres
    migrationsDir: ./migrations

privateKeyPath: ./.keys/ed25519
debug: yes
