name: Go

on: [push]

jobs:

  lint:
    runs-on: ubuntu-latest
    container:
      image: 'golang:1.20-alpine3.17'
    steps:
      - uses: actions/checkout@v3
      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          # Optional: version of golangci-lint to use in form of v1.2 or v1.2.3 or `latest` to use the latest version
          version: v1.51.2

  unit-test:
    runs-on: ubuntu-latest
    container:
      image: 'golang:1.20-alpine3.17'
    steps:
      - uses: actions/checkout@v3
      - name: Run unit tests
        run: make test

  integration-test:
    runs-on: ubuntu-latest
    needs:
      - unit-test
    steps:
      - uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.20'
          cache: true
      - name: Pull postgres
        run: docker pull postgres:15.2-alpine3.17
      - name: Run integration tests
        run: make test-integration
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
